### PR TITLE
fix some cases where groupByNode will work incorrectly

### PR DESCRIPTION
**Pull request by Civil**
Test for that case is still TODO. If you don't want to write it by yourself I'll do that on monday.

### CODE REVIEW

**Comment by Civil** [comment]
Example query that'll fail:
```
groupByNode(la.{01,10,15}.value, 1, "sumSeries")
```

**Comment by Civil** [comment]
Fixed commit message, but still haven't added test for that.

**Comment by Civil** [comment]
Found a bug in this fix, will try to get a proper fix...

**Comment by Civil** [comment]
Added two tests that fails.

**Comment by Civil** [comment]
Got an uglier version of fix that's working and passes all the tests.

**Comment by nnuss** [comment]
Looks ok to me. Perhaps later we'll augment parseExpr to hint the etype we want.

**Pull request merged**
