### PR TITLE
Add support for timeFunction

### PR DESCRIPTION
**Pull request by kerrick-lyft**

### CODE REVIEW

**Comment by dgryski** [comment]
Sorry for not reviewing this sooner.  I'm not sure I'm happy with the special casing for the time in the test function.  However, I don't have any better ideas at the moment other than its own custom test function.  We could do something with adding start/stop times to the test struct, but that would involve touching every single test entry.  Dunno...

**Comment by kerrick-lyft** [comment]
OK, want me to move it into its own test function?

**Comment by dgryski** [comment]
Yes,  that's easiest.

**Comment by kerrick-lyft** [comment]
OK, I moved the test to a separate function. There's now some code duplication between the two functions, wasn't sure the best way to deal with it (or if you consider it a problem).

**Comment by dgryski** [comment]
It's not a problem. We can deduplicate the test code later.   Thanks.

**Pull request merged**
