### PR TITLE
Add support for maxDataPoints parameter

### PR DESCRIPTION
**Pull request by arodland**
This is working for me in production, but needs some review & attention to get tests passing.

### CODE REVIEW

**Comment by dgryski** [comment]
I'll pick this up.

**Comment by deniszh** [comment]
@dgryski @arodland - did you test maxDataPoints after merging #146 ?
For me it still doesn't work, at least with latest Grafana...

**Comment by dgryski** [comment]
I think @Civil test this, but I don't think we have it deployed everywhere across out stack yet.

**Comment by arodland** [comment]
@deniszh yes, I had, and I just re-tested with latest master. It's working fine for me both with grafana and with manual testing.

**Pull request closed without merging**
