### PR TITLE
Added function constantLine

### PR DESCRIPTION
**Pull request by avereha**
The step for this function is until - from. The test for it was failing
because of that(step was 0).

I'm not sure I did the right thing by updating the (from, until) pair
from (0,0) to (0,1) in the tests.

### CODE REVIEW

**Comment by dgryski** [comment]
Please revert the test half of this pull request. It's too invasive right now, and not the proper fix.

**Comment by JaderDias** [comment]
This commit cannot be half-reverted. Every single part of it depends on the other.

**Comment by dgryski** [comment]
It was going to be cleaned up by @avereha and resubmitted. The test for constantLine will be moved to its own function,  thus not requiring changing every single other test entry.

**Comment by JaderDias** [comment]
In my opinion the change makes sense, since "until" is exclusive there can be no valid metric request where from = until

**Pull request merged**
